ab_site_home:
    path:      /{page}
    defaults:  { _controller: ABSiteBundle:Default:index, page: 1 }
    requirements:
        page: \d*

ab_site_contact:
    pattern:  /contact
    defaults: { _controller: ABSiteBundle:Default:contact }
    requirements:
        _method:  GET|POST